### PR TITLE
Jenkins testing

### PR DESCRIPTION
**Pull request by felipelm**
Testing jenkins

### CODE REVIEW

**Comment by sbailey** [comment]
What is the motivation for using Jenkins instead of Travis?  All our other packages use Travis for testing and it would be preferable to keep everyone on the same system, unless Jenkins provides a specific feature that is required for testing qlf-ui and that Travis cannot provide.

**Comment by felipelm** [comment]
@sbailey we are used to test our other applications using jenkins and have a few integrations configured to facilitate our deploys and workflows.

We will keep travis.yml file but will use mainly jenkins at some point.

**Comment by felipelm** [comment]
deploy qlftest

**Comment by felipelm** [comment]
deploy

**Comment by felipelm** [comment]
test

**Pull request closed without merging**
